config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end
  root 'pages#index', as: 'home'
  
  get 'about' => 'pages#about', as: 'about' # <-- That is an Alias
  get 'contact' => 'pages#contact', as: 'contact'
  get 'services' => 'pages#services', as: 'services'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/pages_record.rb
class PagesRecord < ActiveRecord::Base
    self.abstract_class = true
  end

app/models/post.rb
class Post < ActiveRecord::Base
    has_many :comments

    validates :title, presence: true, length: {minimum: 5, maximum: 50}
    validates :body, presence: true, length: {minimum: 25, maximum: 1000}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    http_basic_authentication_with name: "mindy", password: "1234", only: [:destroy]
    
    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(comment_params)

        redirect_to post_path(@post)
    end

    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy

        redirect_to post_path(@post)
    end

    private
        def comment_params
            params.require(:comment).permit(:username, :body)
        end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    # Creating Methods
    def index
        @title ="Welcome"
        @content = "Welcome to the Homepage"
    end

    def about
        @title = "About"
        @content = "Welcome to the About page"
    end

    def contact
        @title = "Contact"
        @content = "Welcome to the Contact page"
    end

    def services
        @title = "Service"
        @content = "Welcome to the Service page"
        @services = ["Web Design", "Web Development", "SEO"]
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  http_basic_authenticate_with name: "mindy", password: "1234", except: [:index, :show]
  
  def index
    # Show all blog posts
    @post = Post.all
  end

  def new
    # Used for new blog posts
    @post = Post.new
  end

  def create
    # Used to create a new blog post
    # render plain: params[:post].inspect
    @post = Post.new(post_params)
    if@post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    # Edit blog post
    @post = Post.find(params[:id])
  end

  def update
    # Used to update blog posts
    @post = Post.find(params[:id])

    if@post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def show
    # Used to show indavidual blogs
    @post = Post.find(params[:id])
  end

  def destroy
    # Used to delete a blog
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  private
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css'%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-color">
      <a class="navbar-brand" href="#">Rails App</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to 'Home', home_path, { :class=>"nav-link" } %>
          </li>
          <li class="nav-item">
            <%= link_to 'About', about_path, { :class=>"nav-link" } %>
          </li>
          <li class="nav-item">
            <%= link_to 'Contact', contact_path, { :class=>"nav-link" } %>
          </li>
          <li class="nav-item">
            <%= link_to 'Services', services_path, { :class=>"nav-link" } %>
          </li>
          <li class="nav-item">
            <%= link_to 'Blog', posts_path, { :class=>"nav-link" } %>
          </li>
        </ul>

        <ul class="navbar-nav">
          <li class="nav-item float-right">
            <%= link_to 'Create Blog Post', new_post_path, { :class=>"nav-link" } %>
          </li>
        </ul>
      </div>
    </nav>

    <div class="container mt-3">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1> <%= @title %> </h1>

<p>
    <%= @content %>
</p>

app/views/pages/contact.html.erb
<h1> <%= @title %> </h1>

<p>
    <%= @content %>
</p>

app/views/pages/index.html.erb
<%= render "pages/partials/content"%>

app/views/pages/partials/_content.html.erb
<%# This is a partial view that can be used in multiple views %>

<h1> <%= @title %> </h1>

<p> <%= @content %> </p>

app/views/pages/services.html.erb
<h1> <%= @title %> </h1>

<p>
    <%= @content %>
</p>

<% for @service in @services %>
    <div class="alert alert-dark">
        <%= @service %>
    </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
    <% if @post.errors.any? %>
        <div class="alert alert-danger">
            <ul>
                <% @post.errors.full_messages.each do |msg| %>
                <li> <%= msg %> </li>
                <%end%>
            </ul>
        </div>
    <% end %>

    <div class="form-group">
        <%= f.label:title %><br>
        <%= f.text_field(:title, {:class => 'form-control'})%>
    </div>

    <div class="form-group">
        <%= f.label:body %><br>
        <%= f.text_area(:body, {:class => 'form-control'})%>
    </div>

    <div>
        <%= f.submit({:class => 'btn btn-post'})%>
    </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Blog Post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Latest Blog Posts</h1>

<div class="card-columns">
    <% @post.each do |post| %>
        <div class="card mt-4">
            <div class="card-header">
                <h4> <%= post.title %> </h4>
            </div>

            <div class="card-body">
                <p>
                    <%= post.body %>
                </p>

                <div class="">
                    <%= link_to 'Read More', post_path(post), { :class=>"btn btn-post" }%>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/posts/new.html.erb
<h1>Create Blog Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<p>
    <%= @post.body %>
</p>

<h3>Comments</h3>

<% @post.comments.each do |comment| %>
    <div class="alert alert-dark">
        <div class="row">
            <h5 class="col-6"><%= comment.username %></h5>
            
            <div class="col-6">
                <%= link_to "[X]",[comment.post, comment], method: :delete, 
                    data: {confirm: "Are you sure ?"}, :class => "btn btn-danger float-right" %>
            </div>
            <div class="clearfix"></div>
        </div>

        <p>
            <%= comment.body %>
        </p>
    </div>
<%end%>

<hr class="mt-5">
<%= link_to "Edit", edit_post_path(@post), {:class => "btn btn-primary"} %>

<%= link_to "Destroy", post_path(@post), method: :delete, 
        data: {confirm: "Are you sure ?"}, :class => "btn btn-danger" %>

<hr class="mt-5">

<h3>Add A Comment</h3>

<%= form_for([@post, @post.comments.build]) do |f| %>
    <div class="form-group">
        <%= f.label:username %><br>
        <%= f.text_field(:username, {:class => 'form-control'})%>
    </div>

    <div class="form-group">
        <%= f.label:comment %><br>
        <%= f.text_area(:body, {:class => 'form-control'})%>
    </div>

    <div class="">
        <%= f.submit({:class => 'btn btn-post'})%>
    </div>
<% end %>